### ISSUE TITLE
Trying to listen 19132 UDP PORT

### ISSUE THREAD

**Issue by MatheusIam** [MarkoPaul0/DatagramTunneler#10]
Hi, i'm having some problem when trying to listen 19132 UDP port, maybe because i am using the program wrongly...

i run these commands: 

./datagramtunneler --server -i 192.168.100.4 -t 19132
./datagramtunneler --client -i 192.168.100.4 -t 127.0.0.1:19132 -u 192.168.100.4:19132

**Comment by MatheusIam** [comment]
![image](https://user-images.githubusercontent.com/26061736/126082090-361c1c8e-3129-49be-bdd1-d46376bb7678.png)

**Comment by MarkoPaul0** [comment]
@MatheusIam sorry for the delay. DatagramTunneler works in the following way:
- the DT server side listens to a UDP multicast group, relay datagrams it receives from that group over a TCP connection to the client, 
- the DT client publishes these datagrams into a new UDP multicast group

I don't think the DT can help you do much with ngrok, because ngrok doesn't deal with UDP multicast as far as I understand. If you have reasons to believe otherwise, send me some doc and I'll see if I can help.
