### ISSUE TITLE
How do i compile it

### ISSUE THREAD

**Issue by shunz19** [MarkoPaul0/DatagramTunneler#2]
I've been googling a lot for a year now and oh boi I'm always looking for exe files in bin folders. I'm a complete newbie and really wanted to learn how to compile these master folders i download from github. Please teach me

**Comment by MarkoPaul0** [comment]
It all depends on the project, however in this case you're dealing with a C++ project with a simple makefile. All you usually have to do is go to the directory containing that makefile and run make.
```
cd <path_to_dgram_tunneler_directory>
make
```
And you're done. Then the executable is gonna be in `<path_to_dgram_tunneler_directory>/bin/datagramtunneler`, which you can run by following the instructions in my repo. It is rather standard to have the executable produced in the ./bin directory, but this may not be the case if the developer decided to write a funny makefile.

Hope this helps! ;)

**Comment by shunz19** [comment]
Thank you, my laptop's os is windows and recently dualboots it with ubuntu. Guess I'll be spending more time on ubuntu now :)

**Comment by BahadirKaya90** [comment]
make command doesn't work when I type it on cmd command screen. I have newbee in this type of things. I want to open server for CS 1.6 I did previous stuff for Ngrok configuration but Now I am stacked here. Please help. How to convert TCP to UDP?

**Comment by MarkoPaul0** [comment]
"cmd command screen" as in Windows cmd.exe? If so even if you install make and a C++ compiler, you won't be able to compile DatagramTunneler because it is not Windows compatible.

**Comment by BahadirKaya90** [comment]
> "cmd command screen" as in Windows cmd.exe? If so even if you install make and a C++ compiler, you won't be able to compile DatagramTunneler because it is not Windows compatible.

Yes on Windows 10 Pro cmd.exe. Isn't it compatible with Windows? I have been advised for your program to port TCP to UDP for windows. I'm surprized to hear that. How can I solve the issue?

**Comment by MarkoPaul0** [comment]
@BahadirKaya90, I have created a new issue to discuss your problem since it is not really related to this ticket. So please continue the discussion on issue #4.

**Comment by BahadirKaya90** [comment]
I am advised here. https://teknoltan.com/modem-port-forwarding-acma-yonlendirme-ip-sabitleme/
A Turkish Forum about portforwarding.

Let me explain you from beginning. Yes I want to play Counter Strike 1.6 with buy distant friends over the same server. For this, I need to setup a UDP server and give them my ip address and the UDP port. Normally I can open ports and invite them easily after some Modem configurations. However, My ISP is assigning me an IP address from a system called "CGN" Because of this my friends cannot be able to connect my server.

So, I searched for other possible solutions on the net and found the above website and applied the instructions but for the last step I needed to convert TCP to UDP since the counter strike is on UDP. But it seems there is no way to do that with your compile.
